### ISSUE TITLE
undo functionality

### ISSUE THREAD

**Issue by gauravgupta566** [janishar/Tutorials#2]
![screenshot 1](https://user-images.githubusercontent.com/18099872/28996738-c48ad19e-79ba-11e7-890c-418c0b2134dc.png)

there is no method for undo

**Comment by gauravgupta566** [comment]
problem solved i change  0.2.4 to  compile 'com.mindorks:placeholderview:0.6.4'

**Comment by janishar** [comment]
Awesome

**Comment by HammadNasir** [comment]
@janishar any solution to undo upto the very first card?
